"""empty message

Revision ID: da9fc7ef9433
Revises: 5425a0feb4dd
Create Date: 2018-06-14 13:34:15.841483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9fc7ef9433'
down_revision = '5425a0feb4dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('click_counter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url', 'click_counter')
    # ### end Alembic commands ###
